[target.aarch64-unknown-linux-gnu]
image="tokio-serial/aarch64-unknown-linux-gnu"

[target.arm-unknown-linux-gnueabi]
image="tokio-serial/arm-unknown-linux-gnueabi"

[target.armv7-unknown-linux-gnueabihf]
image="tokio-serial/armv7-unknown-linux-gnueabihf"

[target.i686-unknown-linux-gnu]
image="tokio-serial/i686-unknown-linux-gnu"

[target.i686-unknown-linux-musl]
image="tokio-serial/i686-unknown-linux-musl"

[target.mips-unknown-linux-gnu]
image="tokio-serial/mips-unknown-linux-gnu"

[target.mipsel-unknown-linux-gnu]
image="tokio-serial/mipsel-unknown-linux-gnu"

[target.powerpc-unknown-linux-gnu]
image="tokio-serial/powerpc-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
image="tokio-serial/x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-musl]
image="tokio-serial/x86_64-unknown-linux-musl"
